// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhON8uomAj_Ee4xC0cTZvxSXrj-GvhD_M',
    appId: '1:52644882225:web:8d859299035bc79e0f7210',
    messagingSenderId: '52644882225',
    projectId: 'ecommerceapp-8770c',
    authDomain: 'ecommerceapp-8770c.firebaseapp.com',
    storageBucket: 'ecommerceapp-8770c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIhM26LIWhhOV-hSvERRQMGs1JzjDVkAc',
    appId: '1:52644882225:android:3359735bb5a6d9f40f7210',
    messagingSenderId: '52644882225',
    projectId: 'ecommerceapp-8770c',
    storageBucket: 'ecommerceapp-8770c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxmFeggmdzzHqkziZPNYDtyLG1NflVz-M',
    appId: '1:52644882225:ios:8f2faa77b397bae90f7210',
    messagingSenderId: '52644882225',
    projectId: 'ecommerceapp-8770c',
    storageBucket: 'ecommerceapp-8770c.firebasestorage.app',
    androidClientId: '52644882225-hk92ol37iov82bgs3ijn8ocolihti82o.apps.googleusercontent.com',
    iosClientId: '52644882225-2ao547baa1o2beucgcu1h18msmuhofkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.spektaStore',
  );

}